// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Strings.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract CodingDojo is Ownable {
    using Strings for uint256;

    // Token name
    string private _name;

    // Token symbol
    string private _symbol;

    // Mapping
    mapping(address => uint256) private _balances;
    mapping(uint256 => string) private _tokenURIs;
    mapping(uint256 => address) private _owners;

    // Counters
    uint256 private _tokenIdCounter = 0;

    //Arrays
    uint256[] private _allTokens;

    /**
     * @dev Initializes the contract by setting a `name` and a `symbol` to the token collection.
     */
    constructor() {
        _name = "CodingDojo";
        _symbol = "CD";
    }

    /**
     * @dev See {IERC721Metadata-name}.
     */
    function name() public view returns (string memory) {
        return _name;
    }

    /**
     * @dev See {IERC721Metadata-symbol}.
     */
    function symbol() public view returns (string memory) {
        return _symbol;
    }

    /**
     * Base URI
     */
    function _baseURI() internal pure returns (string memory) {
        return "ipfs://";
    }

    /**
     * @dev Get current Token ID and increment tokenCounter after mint
     * mint tokenId to address `_mint`
     * set token uri to tokenId `_setTokenURI`
     *
     * Requirements:
     *
     * - `uri` any string/hash that was generated by web3.storage
     * - `to` cannot be the zero address.
     *
     */
    function safeMint(address to, string memory uri) public onlyOwner {
        require(to != address(0), "cannot be zero address");
        uint256 tokenId = _tokenIdCounter;
        _tokenIdCounter++;

        _mint(to, tokenId);

        _setTokenURI(tokenId, uri);
    }

    function _addTokenToAllTokensEnumeration(uint256 tokenId) private {
        _allTokens.push(tokenId);
    }

    /**
     * @dev Mints `tokenId` and transfers it to `to`.
     *
     * WARNING: Usage of this method is discouraged, use {_safeMint} whenever possible
     *
     * Requirements:
     *
     * - `tokenId` must not exist.
     * - `to` cannot be the zero address.
     *
     * Emits a {Transfer} event.
     */
    function _mint(address to, uint256 tokenId) internal virtual {
        require(to != address(0), "cannot be zero address");
        require(!_exists(tokenId), "tokenId must not exist");

        _balances[to] += 1;

        _owners[tokenId] = to;
    }

    /**
     * @dev Sets `_tokenURI` as the tokenURI of `tokenId`.
     *
     * Requirements:
     *
     * - `tokenId` must exist.
     */
    function _setTokenURI(uint256 tokenId, string memory _tokenURI)
        internal
        virtual
    {
        require(!_exists(tokenId), "tokenId must exist");
        _tokenURIs[tokenId] = _tokenURI;
    }

    /**
     * Returns the Uniform Resource Identifier (URI) for tokenId token.
     */
    function tokenURI(uint256 tokenId) public view returns (string memory) {
        require(!_exists(tokenId), "tokenId must exist");

        return string(abi.encodePacked(_baseURI(), _tokenURIs[tokenId]));
    }

    /**
     * @dev Returns whether `tokenId` exists.
     *
     * Tokens can be managed by their owner or approved accounts via {approve} or {setApprovalForAll}.
     *
     * Tokens start existing when they are minted (`_mint`),
     * and stop existing when they are burned (`_burn`).
     */
    function _exists(uint256 tokenId) internal view returns (bool) {
        return _owners[tokenId] != address(0);
    }

    /**
     * @dev See {IERC721Enumerable-totalSupply}.
     */
    function totalSupply() public view returns (uint256) {
        return _allTokens.length;
    }

    /**
     * Returns the owner of the tokenId token.
     * Requirements: tokenId must exist.
     */
    function ownerOf(uint256 tokenId) external view returns (address) {
        return _owners[tokenId];
    }

    /**
     * Returns the owner of the tokenId token.
     */
    function balanceOf(address owner) external view returns (uint256) {
        return _balances[owner];
    }
}
